services:
  # Main App
  - type: web
    name: medicare-app
    env: node
    buildCommand: cd my-app && npm install && npm run build
    startCommand: cd my-app && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        value: https://medicare-app.onrender.com
      - key: NEXT_PUBLIC_SIGNALING_SERVER_URL
        value: https://medicare-signaling.onrender.com
      - key: NEXT_PUBLIC_CHAT_SERVER_URL
        value: https://medicare-chat.onrender.com

  # Signaling Server
  - type: web
    name: medicare-signaling
    env: node
    buildCommand: cd signaling-server && npm install
    startCommand: cd signaling-server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SIGNALING_PORT
        value: 10000
      - key: NEXT_PUBLIC_APP_URL
        value: https://medicare-app.onrender.com

  # Chat Server
  - type: web
    name: medicare-chat
    env: node
    buildCommand: cd chat-server && npm install
    startCommand: cd chat-server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CHAT_PORT
        value: 10000
      - key: NEXT_PUBLIC_APP_URL
        value: https://medicare-app.onrender.com 